[package]
name = "img-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
send-it = "0.1.4"
chrono = "*"

[dependencies.img-common]
path = "../img-common"